name: pre-commit

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build docker image
      run: docker build . --tag ghcr.io/typst-http-api:${{ github.sha }}
