name: Docker Image CI for GHCR

on:
  push:
    tags:
      - 'v*' # Trigger only on tags matching v*

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Extract tag name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push latest tag on main branch tag
        if: github.ref == 'refs/tags/v*'
        run: |
          docker build . --tag ghcr.io/slashformotion/typst-http-api:${{ steps.extract_tag.outputs.TAG_NAME }}
          docker push ghcr.io/slashformotion/typst-http-api:${{ steps.extract_tag.outputs.TAG_NAME }}

